# Generated by Django 2.1.3 on 2018-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='playerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.CharField(max_length=8)),
                ('lives', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('highScore', models.IntegerField(default=0)),
                ('turn', models.IntegerField(default=0)),
            ],
        ),
    ]
